### ISSUE TITLE
RuntimeError: index 2 is out of bounds for dimension 0 with size 2

### ISSUE THREAD

**Issue by 1261017506** [JiaRenChang/PSMNet#126]
when i python finetune.py ,i see the error:epoch 1 total training loss = 0.427
Traceback (most recent call last):
  File "finetune.py", line 192, in <module>
    main()
  File "finetune.py", line 166, in main
    test_loss = test(imgL,imgR, disp_L)
  File "finetune.py", line 130, in test
    disp_true[index[0][:], index[1][:], index[2][:]] = np.abs(true_disp[index[0][:], index[1][:], index[2][:]]-pred_disp[index[0][:], index[1][:], index[2][:]])
RuntimeError: index 2 is out of bounds for dimension 0 with size 2
please tell me how to solve,thank you

**Comment by JiaRenChang** [comment]
@1261017506 
Hi, would you make sure your group truth or predicted disparity map is a 3D tensor ? (batchxHxW)

**Comment by 1261017506** [comment]
你好，我数据集和程序都是按你readme上面准备的，所以应该没有问题吧，就是不知道为什么会出现这个错误，谢谢jiaren。
