### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PSMNet:Missing key(s) in state_dict: "cost_net.cnn.conv0.0.net.0.weight"

### ISSUE THREAD

**Issue by 1261017506** [JiaRenChang/PSMNet#128]
self.disp_score = torch.range(0, max_disp - 1)  # [D]
Traceback (most recent call last):
  File "train.py", line 215, in <module>
    main(args)
  File "train.py", line 75, in main
    model.load_state_dict(state['state_dict'])
  File "/home/cb/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PSMNet:
        Missing key(s) in state_dict: "cost_net.cnn.conv0.0.net.0.weight", "cost_net.cnn.conv0.0.net.1.weight", "cost_net.cnn.conv0.0.net.1.bias", "cost_net.cnn.conv0.0.net.1.running_mean", "cost_net.cnn.conv0.0.net.1.running_var", "cost_net.cnn.conv0.1.net.0.weight", "cost_net.cnn.conv0.1.net.1.weight",

**Comment by xiaoyang151** [comment]
Have you solved it? I have encountered similar problems.

**Comment by sarimmehdi** [comment]
Hi. Did you solve this error? It seems this and many other errors seem to occur when this code is run on Google Colab
