### ISSUE TITLE
size of the tensor

### ISSUE THREAD

**Issue by Huyhust13** [JiaRenChang/PSMNet#142]
file run_submission.sh:
```
python submission.py --datapath ../../2.Data/KITTI/data_scene_flow/testing/ \
                     --loadmodel ../../2.Data/KITTI/pretrained_model_KITTI2015.tar \
```
./run_submission.sh 
Number of model parameters: 5224768
/home/huynv/.virtualenvs/envPy2dl/local/lib/python2.7/site-packages/torch/nn/functional.py:1749: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "submission.py", line 115, in <module>
    main()
  File "submission.py", line 106, in main
    pred_disp = test(imgL,imgR)
  File "submission.py", line 80, in test
    output = model(imgL,imgR)
  File "/home/huynv/.virtualenvs/envPy2dl/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huynv/.virtualenvs/envPy2dl/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/huynv/.virtualenvs/envPy2dl/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/huynv/Data/14.ComputerVision/3DVision/1.DepthEstimate/PSMNet/models/stackhourglass.py", line 118, in forward
    cost[:, refimg_fea.size()[1]:, i, :,:]   = targetimg_fea
RuntimeError: The expanded size of the tensor (312) must match the existing size (311) at non-singleton dimension 3
(envPy2dl) huynv@huynv-Inspiron-3668:/media/huynv/Data/14.ComputerVision/3DVision/1.DepthEstimate/PSMNet$ ./run_submission.sh 
Number of model parameters: 5224768
/home/huynv/.virtualenvs/envPy2dl/local/lib/python2.7/site-packages/torch/nn/functional.py:1749: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "submission.py", line 115, in <module>
    main()
  File "submission.py", line 106, in main
    pred_disp = test(imgL,imgR)
  File "submission.py", line 80, in test
    output = model(imgL,imgR)
  File "/home/huynv/.virtualenvs/envPy2dl/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huynv/.virtualenvs/envPy2dl/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/huynv/.virtualenvs/envPy2dl/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/huynv/Data/14.ComputerVision/3DVision/1.DepthEstimate/PSMNet/models/stackhourglass.py", line 118, in forward
    cost[:, refimg_fea.size()[1]:, i, :,:]   = targetimg_fea
RuntimeError: The expanded size of the tensor (312) must match the existing size (311) at non-singleton dimension 3

**Comment by JiaRenChang** [comment]
@Huyhust13 
If you use your own dataset, the width and height of image should be divisible by 32.

**Comment by Huyhust13** [comment]
> @Huyhust13
> If you use your own dataset, the width and height of image should be divisible by 32.

thank you, i'll test it

**Comment by kanghu-bo** [comment]
请问为啥输入图像的大小可以被32整除还是报类似的错误呢?
