### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by HaixiongLi** [JiaRenChang/PSMNet#154]
I am trying to evaluate on KITTI 2015 test dataset. When I finished one epoch and start to test the error, I am getting this error: My GPU is one 1080Ti,
I am getting this error
`Traceback (most recent call last):
  File "/home/cbird/work/net/sy_psm/finetune.py", line 201, in <module>
    main()
  File "/home/cbird/work/net/sy_psm/finetune.py", line 176, in main
    test_loss = test(imgL, imgR, disp_L)
  File "/home/cbird/work/net/sy_psm/finetune.py", line 127, in test
    output3 = model(imgL, imgR)
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cbird/work/net/sy_psm/models/stackhourglass.py", line 133, in forward
    out2, pre2, post2 = self.dres3(out1, pre1, post1)
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cbird/work/net/sy_psm/models/stackhourglass.py", line 53, in forward
    out = self.conv6(post)  # in:1/8 out:1/4
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/home/cbird/anaconda3/envs/lhx/lib/python2.7/site-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 1.30 GiB (GPU 0; 10.91 GiB total capacity; 8.06 GiB already allocated; 508.50 MiB free; 1.33 GiB cached)`

and, Nvidia-smi is :
Tue Sep 24 11:49:51 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 48%   56C    P2    62W / 250W |   5533MiB / 11169MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1116      G   /usr/lib/xorg/Xorg                           299MiB |
|    0      2880      G   compiz                                       153MiB |
|    0      7451      G   ...pycharm-community-2019.1/jre64/bin/java    26MiB |
|    0     18070      C   .../cbird/anaconda3/envs/lhx/bin/python2.7  5043MiB |
|    0     18838      G   ...pycharm-community-2019.1/jre64/bin/java     3MiB |
|    0     24404      G   /usr/lib/firefox/firefox                       2MiB |
+-----------------------------------------------------------------------------+

**Comment by HaixiongLi** [comment]
solved

**Comment by rtuchman** [comment]
@HaixiongLi How did you solve?

**Comment by saeid-h** [comment]
How?
