### ISSUE TITLE
i met a RuntimeError: The size of tensor a (192) must match the size of tensor b (193) at non-singleton dimension 1.  

### ISSUE THREAD

**Issue by aihaoc** [JiaRenChang/PSMNet#207]
i use torchvision 0.7.0,upsampling

(psmnet) cuiaihao@amax-v:~/PSMNet$ CUDA_VISIBLE_DEVICES=7 python submission.py
Number of model parameters: 5224768
/data/home/cuiaihao/.conda/envs/psmnet/lib/python3.7/site-packages/torch/nn/functional.py:2941: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/data/home/cuiaihao/.conda/envs/psmnet/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/data/home/cuiaihao/.conda/envs/psmnet/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=trilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "submission.py", line 120, in <module>
    main()
  File "submission.py", line 106, in main
    pred_disp = test(imgL,imgR)
  File "submission.py", line 71, in test
    output = model(imgL,imgR)
  File "/data/home/cuiaihao/.conda/envs/psmnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/cuiaihao/.conda/envs/psmnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data/home/cuiaihao/.conda/envs/psmnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/cuiaihao/PSMNet/models/stackhourglass.py", line 155, in forward
    pred3 = disparityregression(self.maxdisp)(pred3)
  File "/data/home/cuiaihao/.conda/envs/psmnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/cuiaihao/PSMNet/models/submodule.py", line 51, in forward
    out = torch.sum(x*self.disp.data,2, keepdim=True)
RuntimeError: The size of tensor a (192) must match the size of tensor b (193) at non-singleton dimension 1

**Comment by ai-liuhao** [comment]
我遇到了和你一样的问题，请问你的问题解决了吗？

**Comment by aihaoc** [comment]
Not yet. I don't know how to do it

**Comment by JiaRenChang** [comment]
Hi, @ai-liuhao @aihaoc 
Please pull this repository and try again.

**Comment by ai-liuhao** [comment]
> Hi, @ai-liuhao @aihaoc
> Please pull this repository and try again.

非常谢谢你！我试了一下你的方法，问题解决了！

**Comment by aihaoc** [comment]
> 嗨，@ ai-liuhao @aihaoc
> 请拉出该存储库，然后重试。

Thank you very much for your help.

**Comment by billwang0923** [comment]
My a and b are 4 times different, is this problem the same?
And which file does the repository refer to?
