### ISSUE TITLE
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'dataset/data_scene_flow/testingimage_2'

### ISSUE THREAD

**Issue by ylkojiug** [JiaRenChang/PSMNet#249]
Traceback (most recent call last):
  File "D:\bangong\2024\daima\PSMNet-master\submission.py", line 42, in <module>
    test_left_img, test_right_img = DA.dataloader(args.datapath)
  File "D:\bangong\2024\daima\PSMNet-master\dataloader\KITTI_submission_loader.py", line 23, in dataloader
    image = [img for img in os.listdir(filepath+left_fold) if img.find('_10') > -1]
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'dataset/data_scene_flow/testingimage_2'

**Comment by zxcv666789** [comment]
你好，你可以将data_scene_flow文件夹中testing中的image_2放到data_scence_flow文件夹下并将它改为testingimage_2
