### ISSUE TITLE
Can you give more details about the training dataset ?

### ISSUE THREAD

**Issue by hurricane2018** [JiaRenChang/PSMNet#28]
Hello,
       Can you give more details about the training dataset ?

**Comment by hurricane2018** [comment]
I download the data from web http://www.cvlibs.net/download.php?file=data_scene_flow.zip. 
However, the error is : 



Traceback (most recent call last):
  File "/home/jiewan/Software/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/home/jiewan/Software/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jiewan/Software/pycharm-community-2017.3.3/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jiewan/deep_learning/point_feature/PSMNet/main.py", line 45, in <module>
    all_left_img, all_right_img, all_left_disp, test_left_img, test_right_img, test_left_disp = lt.dataloader(args.datapath)
  File "/home/jiewan/deep_learning/point_feature/PSMNet/dataloader/listflowfile.py", line 22, in dataloader
    monkaa_path = filepath + [x for x in image if 'monkaa' in x][0]
IndexError: list index out of range

Process finished with exit code 1

**Comment by JiaRenChang** [comment]
Hi, @hurricane2018 
Please go to this website: [Scene Flow Datasets](https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html).
Download RGB cleanpass images and its disparity for three subset: FlyingThings3D, Driving, and Monkaa.
Put them in the same folder.
And rename the folder as: "driving_frames_cleanpass", "driving_disparity", "monkaa_frames_cleanpass", "monkaa_disparity", "frames_cleanpass", "frames_disparity".

**Comment by hurricane2018** [comment]
Thank you so much!
