### ISSUE TITLE
Tensor and mask shapes do not match in testing

### ISSUE THREAD

**Issue by lizolson** [JiaRenChang/PSMNet#98]
I was able to train on SceneFlow data, but when I try to test, I receive the error: 

Traceback (most recent call last):
  File "PSMNet/main.py", line 181, in <module>
    main()
  File "PSMNet/main.py", line 167, in main
    test_loss = test(imgL,imgR, disp_L)
  File "PSMNet/main.py", line 126, in test
    loss = torch.mean(torch.abs(output[mask]-disp_true[mask]))  # end-point-error
RuntimeError: The shape of the mask [3, 540, 960] at index 1 does not match the shape of the indexed tensor [3, 60, 24, 68, 120] at index 1

Any help in solving this would be greatly appreciated, thanks!

**Comment by JiaRenChang** [comment]
@lizolson1 
Would you check the output size?
It seems that the output size is not matched.

**Comment by JiaRenChang** [comment]
@lizolson1 
It's weird. The output dimension should be the same with ground truth disparity.
Did you change anything about the code?

**Comment by shahabe** [comment]
I also wanted to test the original code and I did not change anything at all.
I got the same error as well in the line 62 of submodule.py:

> aaa=x*disp
*** RuntimeError: The size of tensor a (48) must match the size of tensor b (192) at non-singleton dimension 1

 
and these are the sizes:
> ipdb> disp.size()
torch.Size([1, 192, 96, 312])
> ipdb> x.size()
torch.Size([1, 48, 96, 312])

Any help om this issue please.
Thank you.

**Comment by JiaRenChang** [comment]
@shahabe 
It seems that the "x" is not correctly upsampled.
You may check the upsample function setting which should be "trilinear".

**Comment by lizolson1** [comment]
@JiaRenChang 
The upsample is trilinear in the upsample step of the hourglass model, it is bilinear in the output branch's upsample of the feature_extraction function in submodule script. Changing it to trilinear gives an error: Got 4D input, but trilinear needs 5D input.

**Comment by AN-1103** [comment]
> I also wanted to test the original code and I did not change anything at all.
> I got the same error as well in the line 62 of submodule.py:
> 
> > aaa=x*disp
> > *** RuntimeError: The size of tensor a (48) must match the size of tensor b (192) at non-singleton dimension 1
> 
> and these are the sizes:
> 
> > ipdb> disp.size()
> > torch.Size([1, 192, 96, 312])
> > ipdb> x.size()
> > torch.Size([1, 48, 96, 312])
> 
> Any help om this issue please.
> Thank you.

Hello, I also encountered the same problem in the test. Have you solved this problem? Looking forward to your help, thank you~

**Comment by AN-1103** [comment]
@lizolson1 
Hello, I also encountered the same problem in the test. Have you solved it?
Looking forward to your help.
thank you~
